//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JokenPo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogos
    {
        public int idJogo { get; set; }
        public int idPartida { get; set; }
        public int Ponto { get; set; }
        public int idGanhador { get; set; }
        public string Ganhador { get; set; }
        public string Jogador1 { get; set; }
        public string Jogador2 { get; set; }
    }
}
