//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JokenPo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Rodrigo_MVCEntities : DbContext
    {
        public Rodrigo_MVCEntities()
            : base("name=Rodrigo_MVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Jogador> Jogador { get; set; }
        public virtual DbSet<Objetos> Objetos { get; set; }
        public virtual DbSet<Partida> Partida { get; set; }
        public virtual DbSet<Jogos> Jogos { get; set; }
    }
}
